apiVersion: v2
name: paperless-ngx
description: A Helm chart for Paperless-ngx document management system
version: 1.0.0
kubeVersion: ">=1.22.0-0"

maintainers:
  - name: Roy Bales
    email: rbales79@gmail.com
