{{- if .Values.clusterGroup.applicationStacks.ai.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-ai-applicationset
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: charts/applications/ai
    helm:
      values: |
        spec:
{{ .Values.spec | toYaml | indent 10 }}
        topology:
{{ .Values.topology | toYaml | indent 10 }}
        config:
{{ .Values.config | toYaml | indent 10 }}
        clusterGroup:
{{ .Values.clusterGroup | toYaml | indent 10 }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
{{- end }}
