---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: {{ .Release.Name }}-secret
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: PAPERLESS_SECRET_KEY
    - secretKey: admin-password
      remoteRef:
        key: PAPERLESS_ADMIN_PASSWORD
