apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: amd-gpu-device-plugin
  labels:
    app.kubernetes.io/name: amd-gpu-device-plugin
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: amd-gpu-device-plugin
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
