---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: amd-gpu-device-plugin
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    goldilocks.fairwinds.com/enabled: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
