{{- if .Values.acm }}
---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  {{- if .Values.acm.availabilityConfig }}
  availabilityConfig: {{ .Values.acm.availabilityConfig }}
  {{- end }}
{{- end }}
