apiVersion: v2
name: glue-worker
description: A Helm chart for Glue Worker - Flask webhook orchestrator for Paperless pipeline
version: 1.0.0
kubeVersion: ">=1.22.0-0"

maintainers:
  - name: Roy Bales
    email: rbales79@gmail.com
