{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo.fullname" . }}-frontend
  labels:
    {{- include "todo.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: {{ .Values.frontend.service.name }}
  selector:
    {{- include "todo.frontend.selectorLabels" . | nindent 4 }}
{{- end }}
