{{- if .Values.controller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: metallb-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metallb-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metallb-controller
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: controller
        image: {{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        args:
        - --log-level={{ .Values.controller.logLevel }}
        {{- if .Values.controller.webhookMode }}
        - --webhook-mode={{ .Values.controller.webhookMode }}
        {{- end }}
        ports:
        - name: metrics
          containerPort: 7472
          protocol: TCP
        - name: webhook
          containerPort: 9443
          protocol: TCP
        resources:
          {{- toYaml .Values.controller.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
{{- end }}
