apiVersion: v2
description: A Helm chart for deploying AIStor MinIO operator
name: aistor-minio-operator
version: 1.0.0
kubeVersion: ">=1.31.0-0"

maintainers:
  - name: Jonathan Gough
    email: jgough@essextec.com